In [3]:
import pandas as pd

df = pd.read_csv('cleaned_nutrition.csv')
df.head()

,Vitamin C (mg per 100g),Vitamin B11 (mg per 100g),Sodium (mg per 100g),Calcium (mg per 100g),Carbohydrates (g per 100g),food,Iron (mg per 100g),Calories (kcal per 100g),Sugars (g per 100g),Dietary Fiber (g per 100g),Fat (g per 100g),Protein (g per 100g),food_normalized
0,0.082,0.086,0.018,2.8,0.073,margarine with yoghurt,0.027,88.0,0.0,0.0,9.8,0.058,margarine with yoghurt
1,0.400,0.005,0.065,10.2,3.700,sunflower seed butter,0.700,99.0,1.7,0.9,8.8,2.800,sunflower seed butter
2,0.000,0.000,0.000,0.0,0.000,hazelnut oil,0.000,120.0,0.0,0.0,13.6,0.000,hazelnut oil
3,0.000,0.000,0.000,0.0,0.000,menhaden fish oil,0.000,1966.0,0.0,0.0,218.0,0.000,menhaden fish oil
4,0.000,0.000,0.000,0.0,0.000,cod liver fish oil,0.000,123.0,0.0,0.0,13.6,0.000,cod liver fish oil

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3454 entries, 0 to 3453
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Vitamin C (mg per 100g)     3454 non-null   float64
 1   Vitamin B11 (mg per 100g)   3454 non-null   float64
 2   Sodium (mg per 100g)        3454 non-null   float64
 3   Calcium (mg per 100g)       3454 non-null   float64
 4   Carbohydrates (g per 100g)  3454 non-null   float64
 5   food                        3454 non-null   str
 6   Iron (mg per 100g)          3454 non-null   float64
 7   Calories (kcal per 100g)    3454 non-null   float64
 8   Sugars (g per 100g)         3454 non-null   float64
 9   Dietary Fiber (g per 100g)  3454 non-null   float64
 10  Fat (g per 100g)            3454 non-null   float64
 11  Protein (g per 100g)        3454 non-null   float64
 12  food_normalized             3454 non-null   str
dtypes: float64(11), str(2)
memory usage: 350.9 KB

In [5]:
df.isnull().sum()

Vitamin C (mg per 100g)       0
Vitamin B11 (mg per 100g)     0
Sodium (mg per 100g)          0
Calcium (mg per 100g)         0
Carbohydrates (g per 100g)    0
food                          0
Iron (mg per 100g)            0
Calories (kcal per 100g)      0
Sugars (g per 100g)           0
Dietary Fiber (g per 100g)    0
Fat (g per 100g)              0
Protein (g per 100g)          0
food_normalized               0
dtype: int64

In [6]:
df.tail()

,Vitamin C (mg per 100g),Vitamin B11 (mg per 100g),Sodium (mg per 100g),Calcium (mg per 100g),Carbohydrates (g per 100g),food,Iron (mg per 100g),Calories (kcal per 100g),Sugars (g per 100g),Dietary Fiber (g per 100g),Fat (g per 100g),Protein (g per 100g),food_normalized
3449,0.3,0.075,0.3,21.94,25.0,clam chowder,0.7,250.0,0.92,2.0,10.0,12.0,clam chowder
3450,0.3,0.075,0.3,21.94,20.0,crab cakes,0.7,270.0,0.92,2.0,15.0,18.0,crab cakes
3451,0.3,0.075,0.2,21.94,35.0,creme brulee,0.7,300.0,0.92,0.0,16.0,7.0,creme brulee
3452,0.3,0.075,0.3,21.94,30.0,croque madame,0.7,320.0,0.92,1.0,18.0,14.0,croque madame
3453,0.3,0.075,0.3,21.94,40.0,cup cakes,0.7,350.0,0.92,2.0,20.0,6.0,cup cakes